name: UI Performance Check
on: [pull_request]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: mkdir /tmp/artifacts
      - run: npm install
      - run: npm run build
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          branch: ${{ github.ref }}
          outputDirectory: /tmp/artifacts
          sha: ${{ github.sha }}
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts